Boomerang-master/config/routes.rb
Rails.application.routes.draw do

  root to: 'mood#index'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }

  resources :users
  get 'meet', to: 'meet#index'

  get  'meet/:pgid',to: 'meet#index'

  post 'match/update', to:'match#updateResponse'

  resources :users do
    post 'notify', :on => :collection
  end
  resources :mood
  resources :match
  resources :meet

end

Boomerang-master/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Boomerang-master/app/views/layouts/_nav_links_for_auth.html.erb
<li><%= link_to 'Mood', mood_index_path %></li>
<li><%= link_to 'Match', match_index_path %></li>

<% if user_signed_in? %>
  <%# <li><%= link_to 'Mood', mood_path%\\\\\\\\></li> %>

  <%# <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %\\\\\\></li> %>

<% else %>

  <%# <li><%= link_to 'Sign in', new_user_session_path %\\\\\\\\></li>  %>
  <%# <li><%= link_to 'Sign up', new_user_registration_path %\\\\\\\\></li> %>
<% end %>

<li><%= link_to 'Meet', meet_index_path %></li>
<li><%= link_to 'Profile', edit_user_registration_path %></li>

<%
=begin %> my old avatar in menu code -- obsolete
<li> <%= link_to edit_user_registration_path do %>
  <% if user_signed_in? %>
    <% if current_user.avatar? %>
        <%= image_tag current_user.avatar.url(:thumb), class: "round-image-50" %>
      <% else %>
        <%= image_tag "default_profile_image.png", class: "round-image-50" %>
    <% end %>
  <% else %>
    <%= image_tag "default_profile_image.png", class: "round-image-50" %>
  <% end %>
</li>
<% end %>
<%
=end %>

Boomerang-master/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

Boomerang-master/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<%
=begin %>
<li><%= link_to 'About', page_path('about') %></li>
%>
<%
=end %>

Boomerang-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" style="margin-top:0;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>

</html>